services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"