FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Győződj meg róla, hogy az .env fájl a konténerbe is bekerül
ENV PYTHONUNBUFFERED=1

CMD ["python", "app.py"]
